apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: budget-app-run
spec:
  pipelineRef:
    name: budget-app-pipeline
  taskRunTemplate:
    serviceAccountName: tekton-bot  # 👈 fixed location
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: kaniko-workspace-pvc
  params:
    - name: repo-url
      value: https://github.com/KrithikJoshi/makerble-assignment
    - name: image-name
      value: docker.io/krithik2018/budget-app
