apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: budget-app-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
    - name: image-name
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-push-image
      runAfter: [clone-repo]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
