apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: budget-app-run
spec:
  pipelineRef:
    name: budget-app-pipeline
  taskRunTemplate:
    serviceAccountName: tekton-bot 
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: kaniko-workspace-pvc
  params:
    - name: repo-url
      value: https://github.com/sanikavyawahare/Makerble-Assignment 
    - name: image-name
      value: docker.io/saniika18/budget-app
