apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: ${REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}
